### ISSUE TITLE
Getting started instructions fail

### ISSUE THREAD

**Issue by coldino** [Advik-B/CurseForge-API#2]
Tried the simple instructions for getting started and the `.game(...)` method always fails.

```py
>>> from curseforge import CurseClient
>>> from dotenv import dotenv_values
>>> config = dotenv_values()
>>>
>>> curse = CurseClient(config['CURSEFORGE_API_KEY'])
>>> 
>>> curse.game(432)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\Work\Gms\CurseForgeAPI\.venv\Lib\site-packages\curseforge\base.py", line 79, in game
    return CurseGame.from_dict(self.fetch(f"game/{game_id}"))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Work\Gms\CurseForgeAPI\.venv\Lib\site-packages\curseforge\classes\cursegame.py", line 23, in from_dict
    id=data.get("id"),
       ^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get'
>>> 
>>> next(curse.games())
CurseGame(id=78135, name='Demeo', slug='demeo', assets=CurseGameAssets(icon_url='iconUrl', tile_url='tileUrl', cover_url='coverUrl'), status=6, api_status=None, date_modified=None)
```

Tried a number of game IDs, both with and without caching just in case. No luck.

As you can see the `.games()` call after it works, so the API key is working.

**Comment by Advik-B** [comment]
I am extremely sorry for the stupidly late reply
Why the hell doesn't GitHub notify me about this issues, will look into it right away

**Comment by Advik-B** [comment]
Ahh, I see  the issue here, the fetch method is requesting the `/game` path, which does not exist
It should actually fetch `/games/{GAME_ID}`, so thank you for this issue
![image](https://github.com/Advik-B/CurseForge-API/assets/86160411/ad3545c3-926c-4797-af08-71c61050ebdf)

PS: I STILL DONT KNOW WHY GITHUB DID NOT NOTIFY ME ABOUT THIS ISSUE, OCT 3rd!! REALLY!!

**Comment by Advik-B** [comment]
Run:
```
pip install --upgrade curseforge
```
